runtipi/runtipi-appstore

- apps/nextcloud/config.json
- apps/nextcloud/docker-compose.yml
These changes are sourced from many months of tuning for Nextcloud as a part of https://github.com/sethforprivacy/self-hosted-services
> Improve Nextcloud proxy labels and env vars

- apps/plex/config.json
- apps/plex/docker-compose.yml
Update docker tag for Plex to 1.30.1
First time using git/github. Please advise on any errors in this process.
> Update docker tag for Plex to 1.30.1

- apps/plex/config.json
- apps/plex/docker-compose.yml
Update Plex docker tag to 1.30.2
> Update Plex docker tag to 1.30.2

- apps/pihole/config.json
> Fix pihole open button not going to admin page

- apps/plex/config.json
- apps/plex/docker-compose.yml
Update Plex docker tag to 1.31.0
> Update Plex docker tag to 1.31.0

- apps/plex/config.json
- apps/plex/docker-compose.yml
Update Plex docker tag to 1.31.2
> Update Plex docker tag to 1.31.2

- apps/plex/config.json
- apps/plex/docker-compose.yml
Update Plex docker tag to 1.32.0
> Update Plex docker tag to 1.32.0

- apps/vikunja/metadata/description.md
link to try.vikunja.io was wrong, is fixed in pull request
cheers
simon
> fix broken link

- apps/chatgpt-ui/config.json
- apps/chatpad/config.json
- apps/dailytxt/config.json
- apps/deluge/docker-compose.yml
- apps/deluge/metadata/description.md
- Changed categories to "ai" for AI apps
- Added boolean value for DailyTxT
- Change download folder of deluge to follow the others
> chore: small updates to categories and fields

- apps/send/config.json
- apps/send/docker-compose.yml
- DETECT_BASE_URL env removed
- FILE_DIR env added
- redis healthcheck interval increased from 1s to 5s
> chore: Send app improvements

- .github/workflows/auto-merge.yml
- .github/workflows/ci.yml
- .github/workflows/renovate-app-version.yml
- apps/__tests__/apps.test.ts
- apps/adguard/config.json
- apps/autobrr/config.json
- apps/chatgpt-ui/config.json
- apps/deemix/docker-compose.yml
- apps/hello-world/config.json
- apps/hello-world/docker-compose.yml
- apps/minecraft-server/docker-compose.yml
- apps/mixpost-pro/config.json
- apps/openbooks/config.json
- apps/proxitok/config.json
- apps/proxitok/docker-compose.yml
- apps/vikunja/docker-compose.yml
- apps/your-spotify/config.json
- apps/your-spotify/docker-compose.yml
- package.json
- pnpm-lock.yaml
This pull request introduces a new workflow to automerge non-major app version updates
> ci: automerge minor and patch app upgrades

- apps/invidious/config.json
- apps/invidious/docker-compose.yml
Fixes https://github.com/meienberger/runtipi/issues/570
> Fix invidious config

- apps/gitea/data/gitea/gitea/conf/app.ini
https://github.com/meienberger/runtipi/issues/599
> fix: fixed the gitea configuration

- apps/tailscale/docker-compose.yml
Hi there !
Please find bellow a fix for an existing app.
Done 💯
> fix(store): add healthcheck to tailscale

- apps/sshwifty/config.json
Port Conflict with Revolt. CI did not catch the conflict with Secondary Ports. Updated in the app-db
> Update Sshwifty Port

- apps/ghost/config.json
- apps/ghost/docker-compose.yml
- apps/ghost/metadata/description.md
- Fix URL Env to use the right schema
- Added Setup Instructions
> Update Ghost to fix URL

- apps/linkwarden/config.json
- apps/linkwarden/docker-compose.yml
- Update Linkwarden to Official Image
- Add Disable Registration Toggle
> Update Linkwarden Image and Variables

- apps/immich/config.json
- apps/immich/docker-compose.yml
Related to https://github.com/immich-app/immich/discussions/5086, Impending Breaking Changes
> Immich v1.88.0 Breaking Changes

- apps/activepieces/config.json
- apps/activepieces/docker-compose.yml
> Fix Active Pieces URL and PG Healthcheck

- apps/qbittorrent/config.json
- apps/qbittorrent/docker-compose.yml
Reverts runtipi/runtipi-appstore#2147
> Revert "chore(deps): update lscr.io/linuxserver/qbittorrent docker tag to v20"

- apps/deluge/config.json
- apps/deluge/docker-compose.yml
Reverts runtipi/runtipi-appstore#2144
> Revert "chore(deps): update lscr.io/linuxserver/deluge docker tag to v18"

- apps/2fauth/config.json
- apps/2fauth/docker-compose.yml
> fix(2fauth): blank page, added env. vars

- apps/lodestone-core/config.json
> fix(lodestone): adjust data permissions

- apps/scrypted/config.json
- apps/scrypted/docker-compose.yml
> fix(scrypted): bump version

- apps/changedetection/docker-compose.yml
Added a missing environment value and an up-to-date playwright config (still as comment)
> [changedetection] Update browserless comment

- apps/immich/docker-compose.yml
- update the image registry from altran1502 to ghcr.io/immich-app
- Refer: https://github.com/immich-app/immich/blob/v1.93.0/docker/docker-compose.yml
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
> [Immich] Update image tag to use official registry 

- apps/jellyfin/docker-compose.yml
Update of Jellyfin to 10.8.13 - docker-compose,
config file pull request- https://github.com/runtipi/runtipi-appstore/pull/2574
> Update Jellyfin to 10.8.13 - docker-compose.yml

- apps/ghost/config.json
- apps/ghost/docker-compose.yml
Allow user to configure SMTP server on Ghost Application
> [APP] Ghost - Add mail configuration

- apps/wg-easy/config.json
- apps/wg-easy/docker-compose.yml
As shown on the readme they moved to github container registry
> wg-easy: update container registry & version

- apps/jellyfin-vue/config.json
- apps/jellyfin-vue/docker-compose.json
This is a jellyfin-vue update for using dynamic compose. (no other change)
> Add dynamic compose for jellyfin-vue

- apps/jellyfin/config.json
- apps/jellyfin/docker-compose.json
This is a jellyfin update for using dynamic compose. (no other change)
> Add dynamic compose for jellyfin

- apps/lobe-chat/config.json
- apps/lobe-chat/docker-compose.json
This is a lobe-chat update for using dynamic compose. (no other change)
none
> Add dynamic compose for lobe-chat

- apps/olivetin/config.json
- apps/olivetin/docker-compose.json
This is a olivetin update for using dynamic compose. (no other change)
> Add dynamic compose for olivetin

- apps/podfetch/config.json
- apps/podfetch/docker-compose.json
This is a podfetch update for using dynamic compose. (no other change)
> Dynamic compose/podfetch

- apps/searxng/config.json
- apps/searxng/docker-compose.json
This is a searxng update for using dynamic compose. (no other change)
> Add dynamic compose for searxng

- apps/silverbullet/config.json
- apps/silverbullet/docker-compose.json
This is a silverbullet update for using dynamic compose. (no other change)
> Add dynamic compose for silverbullet

- apps/vikunja/config.json
- apps/vikunja/docker-compose.json
This is a vikunja update for using dynamic compose. (no other change)
> Add dynamic compose for vikunja

- apps/qbittorrent/config.json
- apps/qbittorrent/docker-compose.yml
Reverts runtipi/runtipi-appstore#6322
> Revert "Update lscr.io/linuxserver/qbittorrent Docker tag to v20"

- apps/sabnzbd/config.json
- apps/sabnzbd/docker-compose.json
> Add dynamic compose for sabnzbd

- apps/kometa/config.json
- apps/kometa/docker-compose.json
> Add dynamic compose for kometa

- apps/invoice-ninja/config.json
- apps/invoice-ninja/docker-compose.json
- apps/invoice-ninja/docker-compose.yml
Reverts runtipi/runtipi-appstore#7206
> Revert "chore(deps): update invoiceninja/invoiceninja docker tag to v5.11.60" - go back to v5.10

- apps/matrix-conduit/config.json
- apps/matrix-conduit/docker-compose.json
- apps/matrix-conduit/docker-compose.yml
- matrix-conduit: `matrixconduit/matrix-conduit:v0.9.0` → `matrixconduit/matrix-conduit:v0.10.3` (minor)
- matrix-conduit: `matrixconduit/matrix-conduit:v0.9.0` → `matrixconduit/matrix-conduit:v0.10.3` (minor)
> chore(matrix-conduit): update 0.9.0 → 0.10.3 (minor)

- apps/metabase/config.json
- apps/metabase/docker-compose.json
- apps/metabase/docker-compose.yml
- metabase: `metabase/metabase:v0.54.4` → `metabase/metabase:v0.54.10` (patch)
- metabase: `metabase/metabase:v0.54.4` → `metabase/metabase:v0.54.10` (patch)
> chore(metabase): update 0.54.4 → 0.54.10 (patch)

- apps/octobot/config.json
- apps/octobot/docker-compose.json
- apps/octobot/docker-compose.yml
- octobot: `drakkarsoftware/octobot:2.0.9` → `drakkarsoftware/octobot:2.0.10` (patch)
- octobot: `drakkarsoftware/octobot:2.0.9` → `drakkarsoftware/octobot:2.0.10` (patch)
> chore(octobot): update 2.0.9 → 2.0.10 (patch)

- apps/changedetection/config.json
- apps/changedetection/docker-compose.json
- apps/changedetection/docker-compose.yml
- changedetection: `ghcr.io/dgtlmoon/changedetection.io:0.49.15` → `ghcr.io/dgtlmoon/changedetection.io:0.49.18` (patch)
- changedetection: `ghcr.io/dgtlmoon/changedetection.io:0.49.15` → `ghcr.io/dgtlmoon/changedetection.io:0.49.18` (patch)
> chore(changedetection): update 0.49.15 → 0.49.18 (patch)

- apps/bewcloud/config.json
- apps/bewcloud/docker-compose.json
- apps/bewcloud/docker-compose.yml
- bewcloud: `ghcr.io/bewcloud/bewcloud:v1.5.6` → `ghcr.io/bewcloud/bewcloud:v1.7.1` (minor)
- bewcloud: `ghcr.io/bewcloud/bewcloud:v1.5.6` → `ghcr.io/bewcloud/bewcloud:v1.7.1` (minor)
> chore(bewcloud): update 1.5.6 → 1.7.1 (minor)

- apps/eclipse-mosquitto/config.json
- apps/eclipse-mosquitto/docker-compose.json
- apps/eclipse-mosquitto/docker-compose.yml
- eclipse-mosquitto: `eclipse-mosquitto:2.0.20` → `eclipse-mosquitto:2.0.21` (patch)
> chore(eclipse-mosquitto): update 2.0.21 → 2.0.21 (patch)

- apps/halo/config.json
- apps/halo/docker-compose.json
- apps/halo/docker-compose.yml
- halo: `halohub/halo:2.20.19` → `halohub/halo:2.20.21` (patch)
- halo: `halohub/halo:2.20.19` → `halohub/halo:2.20.21` (patch)
> chore(halo): update 2.20.19 → 2.20.21 (patch)

- apps/calcom/config.json
- apps/calcom/docker-compose.json
- apps/calcom/docker-compose.yml
- calcom: `calcom/cal.com:v5.0.19` → `calcom/cal.com:v5.3.4` (minor)
- calcom: `calcom/cal.com:v5.0.19` → `calcom/cal.com:v5.3.4` (minor)
> chore(calcom): update 5.0.19 → 5.3.4 (minor)

- apps/ghost/config.json
- ghost: `ghost:5.118.1` → `ghost:5.120.4` (minor)
- ghost: `ghost:5.118.1` → `ghost:5.120.4` (minor)
> chore(ghost): update 5.118.1 → 5.120.4 (minor)

- apps/tailscale/config.json
- tailscale: `tailscale/tailscale:v1.82.0` → `tailscale/tailscale:v1.84.0` (minor)
- tailscale: `tailscale/tailscale:v1.82.0` → `tailscale/tailscale:v1.84.0` (minor)
> chore(tailscale): update 1.82.0 → 1.84.0 (minor)

- apps/nocodb/config.json
- nocodb: `nocodb/nocodb:0.262.5` → `nocodb/nocodb:0.263.4` (minor)
- nocodb: `nocodb/nocodb:0.262.5` → `nocodb/nocodb:0.263.4` (minor)
> chore(nocodb): update 0.262.5 → 0.263.4 (minor)

- apps/rss/config.json
- rss: `codeberg.org/danb/rss:v1.6.0` → `codeberg.org/danb/rss:v1.6.1` (patch)
- rss: `codeberg.org/danb/rss:v1.6.0` → `codeberg.org/danb/rss:v1.6.1` (patch)
> chore(rss): update 1.6.0 → 1.6.1 (patch)

- apps/cloudflared/config.json
- cloudflared: `wisdomsky/cloudflared-web:2025.4.0` → `wisdomsky/cloudflared-web:2025.4.2` (patch)
- cloudflared: `wisdomsky/cloudflared-web:2025.4.0` → `wisdomsky/cloudflared-web:2025.4.2` (patch)
> chore(cloudflared): update 2025.4.0 → 2025.4.2 (patch)

- apps/immich/config.json
- immich: `ghcr.io/immich-app/immich-server:v1.132.3` → `ghcr.io/immich-app/immich-server:v1.134.0` (minor)
- immich-machine-learning: `ghcr.io/immich-app/immich-machine-learning:v1.130.3` → `ghcr.io/immich-app/immich-machine-learning:v1.134.0` (minor)
- immich-db: `tensorchord/pgvecto-rs:pg14-v0.2.0` → `tensorchord/pgvecto-rs:pg14-v0.4.0` (minor)
- immich: `ghcr.io/immich-app/immich-server:v1.132.3` → `ghcr.io/immich-app/immich-server:v1.134.0` (minor)
- immich-machine-learning: `ghcr.io/immich-app/immich-machine-learning:v1.131.2` → `ghcr.io/immich-app/immich-machine-learning:v1.134.0` (minor)
- immich-db: `tensorchord/pgvecto-rs:pg14-v0.2.0` → `tensorchord/pgvecto-rs:pg14-v0.4.0` (minor)
> chore(immich): update 1.132.3 → 1.134.0 (minor)

- apps/homeassistant-1/config.json
- homeassistant-1: `ghcr.io/home-assistant/home-assistant:2025.4.4` → `ghcr.io/home-assistant/home-assistant:2025.5.3` (minor)
- homeassistant-1: `ghcr.io/home-assistant/home-assistant:2025.4.4` → `ghcr.io/home-assistant/home-assistant:2025.5.3` (minor)
> chore(homeassistant-1): update 2025.4.4 → 2025.5.3 (minor)

- apps/mixpost/config.json
- mixpost: `inovector/mixpost:v2.1.3` → `inovector/mixpost:v2.2.0` (minor)
- mixpost: `inovector/mixpost:v2.1.3` → `inovector/mixpost:v2.2.0` (minor)
> chore(mixpost): update 2.1.3 → 2.2.0 (minor)

- apps/lobe-chat/config.json
- lobe-chat: `lobehub/lobe-chat:1.83.8` → `lobehub/lobe-chat:1.88.18` (minor)
- lobe-chat: `lobehub/lobe-chat:1.83.8` → `lobehub/lobe-chat:1.88.18` (minor)
> chore(lobe-chat): update 1.83.8 → 1.88.18 (minor)

- apps/grist/config.json
- apps/grist/docker-compose.json
- apps/grist/docker-compose.yml
- grist: `gristlabs/grist:1.5.2` → `gristlabs/grist:1.6.0` (minor)
- grist: `gristlabs/grist:1.5.2` → `gristlabs/grist:1.6.0` (minor)
> chore(grist): update 1.5.2 → 1.6.0 (minor)

- apps/maintainerr/config.json
- apps/maintainerr/docker-compose.json
- apps/maintainerr/docker-compose.yml
- maintainerr: `ghcr.io/jorenn92/maintainerr:2.16.0` → `ghcr.io/jorenn92/maintainerr:2.17.0` (minor)
- maintainerr: `ghcr.io/jorenn92/maintainerr:2.16.0` → `ghcr.io/jorenn92/maintainerr:2.17.0` (minor)
> chore(maintainerr): update 2.16.0 → 2.17.0 (minor)

- apps/ollama-nvidia/config.json
- apps/ollama-nvidia/docker-compose.json
- apps/ollama-nvidia/docker-compose.yml
- ollama-nvidia: `ollama/ollama:0.8.0` → `ollama/ollama:0.9.0` (minor)
- ollama-nvidia: `ollama/ollama:0.8.0` → `ollama/ollama:0.9.0` (minor)
> chore(ollama-nvidia): update 0.8.0 → 0.9.0 (minor)

- apps/ollama-amd/config.json
- apps/ollama-amd/docker-compose.json
- apps/ollama-amd/docker-compose.yml
- ollama-amd: `ollama/ollama:0.8.0-rocm` → `ollama/ollama:0.9.0-rocm` (minor)
- ollama-amd: `ollama/ollama:0.8.0-rocm` → `ollama/ollama:0.9.0-rocm` (minor)
> chore(ollama-amd): update 0.8.0 → 0.9.0 (minor)

- apps/ollama-cpu/config.json
- apps/ollama-cpu/docker-compose.json
- apps/ollama-cpu/docker-compose.yml
- ollama-cpu: `ollama/ollama:0.8.0` → `ollama/ollama:0.9.0` (minor)
- ollama-cpu: `ollama/ollama:0.8.0` → `ollama/ollama:0.9.0` (minor)
> chore(ollama-cpu): update 0.8.0 → 0.9.0 (minor)

- apps/dozzle/config.json
- apps/dozzle/docker-compose.json
- apps/dozzle/docker-compose.yml
- dozzle: `amir20/dozzle:v8.12.18` → `amir20/dozzle:v8.12.19` (patch)
- dozzle: `amir20/dozzle:v8.12.18` → `amir20/dozzle:v8.12.19` (patch)
> chore(dozzle): update 8.12.18 → 8.12.19 (patch)

- apps/lobe-chat/config.json
- apps/lobe-chat/docker-compose.json
- apps/lobe-chat/docker-compose.yml
- lobe-chat: `lobehub/lobe-chat:1.88.18` → `lobehub/lobe-chat:1.88.20` (patch)
- lobe-chat: `lobehub/lobe-chat:1.88.18` → `lobehub/lobe-chat:1.88.20` (patch)
> chore(lobe-chat): update 1.88.18 → 1.88.20 (patch)

- apps/tubearchivist/config.json
- apps/tubearchivist/docker-compose.json
Fixed a breaking change coming from [v0.5.0](https://github.com/tubearchivist/tubearchivist/releases/tag/v0.5.0)
> fix : tubearchivist redis connection

- apps/nextcloud/config.json
- apps/nextcloud/docker-compose.json
These labels were dysfunctional and needs to be rewritten completely.
> Nextcloud: remove extraLabels

- apps/trilium/config.json
- apps/trilium/docker-compose.json
- apps/trilium/docker-compose.yml
Trilium repo has been transferred to TriliumNext and have received several updates
> Trilium: update app and source repo

- apps/invidious/config.json
- apps/invidious/docker-compose.json
The invidious-companion will replace inv-seg-helper and the need to generated a trusted session token.
It will also make sure to keep up to follow Youtube updates.
> Invidious: add invidious-companion

- apps/immich/config.json
- apps/immich/docker-compose.json
- apps/immich/docker-compose.yml
> immich: update to v2 (stable release)
