runtipi/runtipi-appstore

apps/littlelink-custom/docker-compose.yml
apps/littlelink-custom/metadata/description.md

LittleLink Custom Is currently broken, and it seems to be an issue with Traefik.
What this Fixes (So Far)
- Setup can be completed using the local IP (When trying to use the reverse proxy domain, it redirects to http after the 4th step)
- Should fix the permission issue, and enable https redirects by defualt (does not work for setup though)
Feel free to drop any suggestions out on this one!

LittleLink Reverse Proxy Issues

---

apps/n8n/config.json
apps/n8n/docker-compose.yml
apps/n8n/metadata/description.md

Updated to the latest version and added an environment variable for the domain which is necessary when setting up integrations that have OAUTH2 callbacks, otherwise the callback URL is localhost, which is not functional.
One thing I am not clear on is what ${APP_DOMAIN} returns if the URL is not set to exposed inside of Tipi. Does this need to be conditional?

Update tipi version and added URL environment variable

---

apps/docker-compose.common.yml

This PR fix this warn log:
$ runtipi/logs/app.log
```
2023-08-15T23:49:00.780Z > EventDispatcher: app efpm5oo finished with message: Starting app script
time="2023-08-16T01:48:59+02:00" level=warning msg="network tipi_main_network: network.external.name is deprecated. Please set network.name with external: true"
```

fix(common):  network.external.name is deprecated

---

apps/jackett/config.json
apps/jackett/docker-compose.yml

Jackett gets updated by renovate bot *very* frequently - If you check the version tag it's now up at 80 updates. I think for this use case it makes a lot of sense to just put it at `latest`. It's a web crawler, if you use the old release of a web crawler it's usually just broken. And the constant updating is annoying.

Make Jackett use latest version

---

apps/pihole/config.json
apps/pihole/docker-compose.yml

Pihole had an error in version 1.6.0 in the docker-compose file and it wouldn't start, this is a simple fix for that.

Fix pihole error.

---

apps/halo/config.json
apps/halo/docker-compose.yml

Remove the configuration of the initial administrator, and the registration of the administrator on the initialization page is already supported in 2.9.

chore: update halo config

---

apps/forgejo/docker-compose.yml

Forgejo container was not using the correct db password resulting in an error when trying to run the app

fix(forgejo): correct db password

---

apps/ghostfolio/config.json
apps/ghostfolio/docker-compose.yml
apps/jellyfin/config.json
apps/jellyfin/docker-compose.yml
apps/radarr/config.json
apps/radarr/docker-compose.yml

Some assorted app updates that weren't picked up by mend renovate. Also I updated Ghostfolio to 2.10, it all works. You can then also close https://github.com/meienberger/runtipi-appstore/pull/1176 as superseded.

App updates

---

apps/kavita/config.json
apps/kavita/docker-compose.yml

The [new release of Kavita](https://github.com/Kareadita/Kavita/releases/tag/v0.7.9) moved the image to a [new repository in Docker Hub](https://hub.docker.com/r/jvmilazz0/kavita) so I'm reflecting that in the Tipi app.

Switch to new Kavita image

---

apps/gitea/data/gitea/gitea/conf/app.ini.template

See #1423 for details for PR reason.
From testing I was able to do on my local machine theses are the manual testing I was able to do successfully.
- Account creation works for non exposed app 
- URL's for clone are correct for non exposed app. (HTTP(s) + SSH)
- Able to push through HTTP(S) URL
Was not able to test with an exposed app but the `app.ini` did show correct values compared to manual one I used in my personal server's config.
Was ***not able to push though SSH*** on a non exposed app. I'm not sure why but think it has to do with my local machine. This should be verified by someone else though.

Making settings dynamic (Gitea)

---

apps/changedetection/docker-compose.yml

Chrome container image is 1.17gb in size and quite heavy. Since its not required by changedetection it would be just a custom user config.

fix(changedetection): remove chrome container

---

renovate.json

Adds an Automerge blocker, but will create PRs for Apps with often Breaking Changes.

Renovate Automerge Blocker

---

apps/nextcloud/config.json
apps/nextcloud/docker-compose.yml

Nextcloud 25.0.13 is the last update in the v25 branch, after that this major version is EOL. However Nextcloud cannot gracefully upgrade to the latest major version v27, because there's some internal migrations in Nextcloud that won't work between two major versions. So I upgraded the app to the latest v26 image instead, which is `26.0.8`.

Update Nextcloud to v26

---

apps/calcom/config.json
apps/calcom/docker-compose.yml

- Adds email server username env var and form field
- Adds new env var that is required after the auto-update to 3.7.16 (`DATABASE_DIRECT_URL`)
- Changes encryption key form field length to 32

Bug fixes for Calcom

---

apps/atuin/docker-compose.yml

- commit 29112c8 changed atuin volume to `${APP_DATA_DIR}/data/config` and this causes the database to fail because the data dir is no longer empty
- this commit adds a dedicated directory 'postgres' for database volume
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

fix: atuin database not initialiazing on fresh install

---

apps/atuin/config.json
apps/atuin/docker-compose.yml

If i understand things correctly this will enlist Atuin in Renovate docker tag updates and thereby into Tipi UI-managed updates, which I think is also Tipi best practice and Atuin's maintainers' suggestion - i just didn't know enough when i opened the original PR.

[APP] Atuin: switch to explicit tag

---

apps/bitcoind/config.json

I see that in some PR there is a commit that update the version in the config with the same version in the docker-comopse (for [example](https://github.com/runtipi/runtipi-appstore/pull/3404/commits/01e2f669b698da96eea2e1050b7cb2f863f3f0ca)), but idk why that didnt happend in #3260.

Fix: update version in config.json (app/bitcoind)

---

apps/databag/config.json
apps/databag/docker-compose.json

This is a databag update for using dynamic compose. (no other change)

Add dynamic compose for databag

---

apps/esphome/config.json
apps/esphome/docker-compose.json

This is a esphome update for using dynamic compose. (no other change)

Add dynamic compose for esphome

---

apps/homarr/config.json
apps/homarr/docker-compose.json

This is a homarr update for using dynamic compose. (no other change)

Add dynamic compose for homarr

---

apps/lidarr-deemix/config.json
apps/lidarr-deemix/docker-compose.json

This is a lidarr-deemix update for using dynamic compose. (no other change)

Add dynamic compose for lidarr-deemix

---

apps/lidarr/config.json
apps/lidarr/docker-compose.json

This is a lidarr update for using dynamic compose. (no other change)

Add dynamic compose for lidarr

---

apps/memos/config.json
apps/memos/docker-compose.json

This is a memos update for using dynamic compose. (no other change)
none

Add dynamic compose for memos

---

apps/trilium/config.json
apps/trilium/docker-compose.json

This is a trilium update for using dynamic compose. (no other change)
none

Add dynamic compose for trilium

---

apps/wizarr/config.json
apps/wizarr/docker-compose.json

This is a wizarr update for using dynamic compose. (no other change)

Add dynamic compose for wizarr

---

apps/whoogle/config.json
apps/whoogle/docker-compose.json

This is a whoogle update for using dynamic compose. (no other change)
none

Add dynamic compose for whoogle

---

apps/linkwarden/config.json
apps/linkwarden/docker-compose.json

This is a linkwarden update for using dynamic compose. (no other change)

Add dynamic compose for linkwarden

---

apps/gotify/config.json
apps/gotify/docker-compose.json

This is a gotify update for using dynamic compose. (no other change)

Add dynamic compose for gotify

---

apps/grav/config.json
apps/grav/docker-compose.json

This is a grav update for using dynamic compose. (no other change)

Add dynamic compose for grav

---

apps/kapowarr/config.json
apps/kapowarr/docker-compose.json
apps/kapowarr/docker-compose.yml

This is a kapowarr update for using dynamic compose. (no other change)
none

Dynamic compose/kapowarr

---

apps/zipline/config.json
apps/zipline/docker-compose.json

This is a zipline update for using dynamic compose. (no other change)
​Specific instructions verified :

Add dynamic compose for zipline

---

apps/komga/config.json
apps/komga/docker-compose.json

This is a komga update for using dynamic compose. (no other change)

Add dynamic compose for komga

---

apps/nodered/config.json
apps/nodered/docker-compose.json

This is a nodered update for using dynamic compose. (no other change)
none

Add dynamic compose for nodered

---

apps/pingvin-share/config.json
apps/pingvin-share/docker-compose.json

This is a pingvin-share update for using dynamic compose. (no other change)
none

Add dynamic compose for pingvin-share

---

apps/planning-poker/config.json
apps/planning-poker/docker-compose.json

This is a planning-poker update for using dynamic compose. (no other change)

Add dynamic compose for planning-poker

---

apps/ryot/config.json
apps/ryot/docker-compose.json

This is a ryot update for using dynamic compose. (no other change)

Add dynamic compose for ryot

---

apps/wekan/config.json
apps/wekan/docker-compose.json

This is a wekan update for using dynamic compose. (no other change)

Add dynamic compose for wekan

---

apps/librephotos/config.json
apps/librephotos/docker-compose.json

This is a librephotos update for using dynamic compose. (no other change)
- 💾 Update on existing data

Add dynamic compose for librephotos

---

apps/n8n/config.json
apps/n8n/docker-compose.json

This is a n8n update for using dynamic compose. (no other change)

Add dynamic compose for n8n (v0)

---

apps/owncast/config.json
apps/owncast/docker-compose.json

This is a owncast update for using dynamic compose. (no other change)
none

Add dynamic compose for owncast

---

apps/shlink/config.json
apps/shlink/docker-compose.json

This is a shlink update for using dynamic compose. (no other change)

Add dynamic compose for shlink

---

apps/viewtube/config.json
apps/viewtube/docker-compose.json

This is a viewtube update for using dynamic compose. (no other change)

Dynamic compose/viewtube

---

apps/libretranslate/config.json
apps/libretranslate/docker-compose.json

This is a libretranslate update for using dynamic compose. (no other change)

Add dynamic compose for libretranslate

---

apps/overseerr/config.json
apps/overseerr/docker-compose.json

This is a overseerr update for using dynamic compose. (no other change)

Add dynamic compose for overseerr

---

apps/privatebin/config.json
apps/privatebin/docker-compose.json

This is a privatebin update for using dynamic compose. (no other change)

Add dynamic compose for privatebin

---

apps/radarr/config.json
apps/radarr/docker-compose.json

This is a radarr update for using dynamic compose. (no other change)

Add dynamic compose for radarr

---

apps/readarr/config.json
apps/readarr/docker-compose.json

This is a readarr update for using dynamic compose. (no other change)

Add dynamic compose for readarr

---

apps/send/config.json
apps/send/docker-compose.json

This is a send update for using dynamic compose. (no other change)

Add dynamic compose for send

---

apps/sonarr/config.json
apps/sonarr/docker-compose.json

This is a sonarr update for using dynamic compose. (no other change)

Add dynamic compose for sonarr

---

apps/uptime-kuma/config.json
apps/uptime-kuma/docker-compose.json

This is a uptime-kuma update for using dynamic compose. (no other change)

Add dynamic compose for uptime-kuma

---

apps/whisparr/config.json
apps/whisparr/docker-compose.json

This is a whisparr update for using dynamic compose. (no other change)

Add dynamic compose for whisparr

---

apps/onedev/config.json
apps/onedev/docker-compose.json

This is a onedev update for using dynamic compose. (no other change)

Add dynamic compose for onedev

---

apps/openbooks/config.json
apps/openbooks/docker-compose.json

This is a openbooks update for using dynamic compose. (no other change)

Add dynamic compose for openbooks

---

apps/plex/config.json
apps/plex/docker-compose.json

This is a plex update for using dynamic compose. (no other change)

Add dynamic compose for plex

---

apps/drawio/config.json
apps/drawio/docker-compose.json

This is a drawio update for using dynamic compose.
All data is on client

Add dynamic compose for drawio

---

apps/mylar3/config.json
apps/mylar3/docker-compose.json

This is a mylar3 update for using dynamic compose.

Add dynamic compose for mylar3

---

apps/proxitok/config.json
apps/proxitok/docker-compose.json

This is a proxitok update for using dynamic compose.
- Tiktok scrapper broken (can't go further)

Add dynamic compose for proxitok

---

apps/homeassistant/config.json
apps/homeassistant/docker-compose.json

This is a homeassistant update for using dynamic compose. (no other change)
- 💾 Update on existing data

Add dynamic compose for homeassistant (unexposed)

---

apps/octobot/config.json
apps/octobot/docker-compose.json

This is a octobot update for using dynamic compose.
- 🏷 DNS (skipped)

Add dynamic compose for octobot

---

apps/tooljet/config.json
apps/tooljet/docker-compose.json

This is a tooljet update for using dynamic compose.
- App outdated and broken, need rework

Add dynamic compose for tooljet

---

apps/homebridge/config.json
apps/homebridge/docker-compose.json

This is a homebridge update for using dynamic compose.

Add dynamic compose for homebridge

---

apps/suwayomi/config.json
apps/suwayomi/docker-compose.json

This is a suwayomi update for using dynamic compose.

Add dynamic compose for suwayomi

---

apps/qbittorrent/config.json
apps/qbittorrent/docker-compose.json

This is a qbittorrent update for dynamic compose.
- 🏷 DNS (skipped)

Add dynamic compose for qbittorrent

---

apps/rsshub/config.json
apps/rsshub/docker-compose.json

This is a rsshub update for dynamic compose.

Dynamic compose/rsshub

---

apps/sftpgo/config.json
apps/sftpgo/docker-compose.json

This is a sftpgo update for dynamic compose.

Add dynamic compose for sftpgo

---

apps/tubearchivist/config.json
apps/tubearchivist/docker-compose.json

This is a tubearchivist update for dynamic compose.
-  🙉 Expose (skipped)
- 🏷 DNS (skipped)

Add dynamic compose for tubearchivist

---

apps/netbootxyz/config.json
apps/netbootxyz/docker-compose.json

Add dynamic compose for netbootxyz

---

apps/mqttx/config.json
apps/mqttx/docker-compose.json

Add dynamic compose for mqttx

---

apps/obsidian-livesync/config.json
apps/obsidian-livesync/docker-compose.json
apps/obsidian-livesync/docker-compose.yml

- obsidian-livesync: `couchdb:3.1.2` → `couchdb:3.5.0` (minor)
- obsidian-livesync: `couchdb:3.1.2` → `couchdb:3.5.0` (minor)

chore(obsidian-livesync): update 3.1.2 → 3.5.0 (minor)

---

apps/paperless-ngx/config.json
apps/paperless-ngx/docker-compose.json
apps/paperless-ngx/docker-compose.yml

- gotenberg: `gotenberg/gotenberg:8.20` → `gotenberg/gotenberg:8.21` (minor)

chore(paperless-ngx): update 2.16.2 → 2.16.2 (minor)

---

apps/immich/config.json
apps/immich/docker-compose.json
apps/immich/docker-compose.yml

Addressing the breaking change introduced with [v0.133](https://github.com/immich-app/immich/releases/tag/v1.133.0) :
Image used is now : **ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0**
`healtcheck` and `command` instructions are not necessary anymore.

Immich : change DB image to 

---

apps/notemark/config.json
apps/notemark/docker-compose.json
apps/notemark/docker-compose.yml

- notemark: `ghcr.io/enchant97/note-mark-frontend:0.15.4` → `ghcr.io/enchant97/note-mark-frontend:0.16.0` (minor)
- notemark-backend: `ghcr.io/enchant97/note-mark-backend:0.15.4` → `ghcr.io/enchant97/note-mark-backend:0.16.0` (minor)
- notemark: `ghcr.io/enchant97/note-mark-frontend:0.15.4` → `ghcr.io/enchant97/note-mark-frontend:0.16.0` (minor)
- notemark: `ghcr.io/enchant97/note-mark-frontend:0.15.4` → `ghcr.io/enchant97/note-mark-frontend:0.16.0` (minor)
- notemark-backend: `ghcr.io/enchant97/note-mark-backend:0.15.4` → `ghcr.io/enchant97/note-mark-backend:0.16.0` (minor)

chore(notemark): update 0.15.4 → 0.16.0 (minor)
